Acme\PromoanimalBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: Acme\PromoanimalBundle\Repository\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        price:
            type: decimal
            precision: 10
            scale: '2'
        description:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
